name: CI

on:
  push:
    branches:
      - master
env:
  REPOSITORY_PATH: https://${{secrets.ACCESS_TOKEN}}@github.com/
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@gmail.com"
      - name: pull-code
        uses: actions/checkout@v2
      - name: install-node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: install-dependencies
        run: |
          npm ci --legacy-peer-deps
      - name: lint
        run: |
          npm run lint
      - name: hook-code
        run: |
          npm run hook-code
      - name: test
        run: |
          npm run test:ci
      - name: build
        run: |
          npm run build
      - id: publish
        name: publish
        uses: JS-DevTools/npm-publish@v1
        if: ${{ github.repository_owner	== 'wszgrcy' }}
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          package: ./dist/package.json
      - if: ${{ github.repository_owner	== 'wszgrcy' && steps.publish.outputs.type != 'none' }}
        run: |
          echo "[${{ steps.publish.outputs.type }}]Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
          git tag v${{steps.publish.outputs.version}}
          git push origin v${{steps.publish.outputs.version}}
